# This is a basic workflow to help you get started with Actions

name: NJUcheckin

on: push
#    schedule:
#    - cron: '35 02 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Prepare environment
        run: pip install beautifulsoup4 lxml requests PyExecJs
      - name: Runapp
        id: run
        run: python njucheckin.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: Send mail
        uses: dawidd6/action-send-mail@master
        
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAILUSERNAME }}
          password: ${{ secrets.MAILPASSWORD }}
          subject: 每日打卡信息
          body:  file://email.txt
          to: ${{ secrets.RECEIVERMAILUSERNAME }}
          from: GitHub Actions
          content_type: text/html
